### ISSUE TITLE
Dashboard App can't install watchapp

### ISSUE THREAD

**Issue by vladimir-poleh** [C-D-Lewis/dashboard#6]
Dashboard is crashing when I'm pressing "Install/Update WatchApp" button.

Dashboard App version: 4.13
Device: OnePlus 5, Android 9.

Error log:
```
Process: com.wordpress.ninedof.dashboard, PID: 10327
    android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.wordpress.ninedof.dashboard/files/dashboard.pbw exposed beyond app through Intent.getData()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1978)
        at android.net.Uri.checkFileUriExposed(Uri.java:2371)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:10260)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:10213)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1854)
        at android.app.ContextImpl.startActivity(ContextImpl.java:920)
        at android.app.ContextImpl.startActivity(ContextImpl.java:891)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
        at util.PebbleUtils.sideloadInstall(PebbleUtils.java:51)
        at activity.Landing$3.onClick(Landing.java:167)
        at android.view.View.performClick(View.java:6669)
        at android.view.View.performClickInternal(View.java:6638)
        at android.view.View.access$3100(View.java:789)
        at android.view.View$PerformClick.run(View.java:26145)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

I think that it is related to this [SO question](https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed).

**Comment by C-D-Lewis** [comment]
Upgrading from SDK 19 to 29... So much broken... 

I can replace the native file install with a link to the Rebble app store, but the communication with Pebble Android SDK also appears to break horribly. Need to install the Pebble SDK again and hope I can get logs...

**Comment by vladimir-poleh** [comment]
Yes, WatchApp is not working too. I have this in Logcat when trying to open WatchApp:

```
2020-02-04 02:39:16.710 1356-3858/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=com.getpebble.action.app.RECEIVE flg=0x10 (has extras) } to com.wordpress.ninedof.dashboard/background.PebbleReceiver
```

**Comment by C-D-Lewis** [comment]
This is not a good sign, my gut tells me. Will revisit another night soon.

**Comment by vladimir-poleh** [comment]
I'll try to build and debug it by myself. It seems that fix for the broadcast is not hard thing.

**Comment by vladimir-poleh** [comment]
Android 8+ changed a lot in the security. Trivial broadcast handler registration resolved problem with app opening but some functionality is not working: Hotspot, Find My Phone, Auto Brightness.

**Comment by vladimir-poleh** [comment]
Added pull request #7. No need to update WatchApp.

**Comment by C-D-Lewis** [comment]
Updated to point to Rebble appstore.
